logging:
  path: /data/log/common-example-b

server:
  port: 9999
  servlet:
    context-path: /common-example-b

spring:
  application:
    name: common-example-b
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:h2test
    username: root
    password: root
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.cache.use_second_level_cache: false
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      hibernate.enable_lazy_load_no_trans: true
      hibernate.ejb.interceptor: com.github.hicolors.leisure.common.jpa.customiz.interceptor.BizInterceptor
    open-in-view: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true



warning:
  dingtalk: https://oapi.dingtalk.com/robot/send?access_token=099551a192492077a922a5d1aa7e1a060b0fd18890f021c0e4298013d4dcb5c2

url:
  example-a: http://127.0.0.1:8888/example-a/