logging:
  path: /data/log/common-example-zuul

server:
  port: 7777

warning:
  dingtalk: https://oapi.dingtalk.com/robot/send?access_token=099551a192492077a922a5d1aa7e1a060b0fd18890f021c0e4298013d4dcb5c2


url:
  example-a: http://127.0.0.1:8888/example-a/
  example-b: http://127.0.0.1:9999/example-b/
zuul:
  routes:
    common-example-a:
      path: /common-example-a/**
      url: http://127.0.0.1:8888/
      stripPrefix: false