logging:
  path: /data/log/common-example-b

server:
  port: 9999
  servlet:
    context-path: /common-example-b

spring:
  application:
    name: /common-example-b
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://47.105.97.16:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.cache.use_second_level_cache: false
      hibernate.show_sql: true
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      hibernate.enable_lazy_load_no_trans: true
      hibernate.ejb.interceptor: com.github.hicolors.leisure.common.jpa.customiz.interceptor.BizInterceptor
    open-in-view: true


warning:
  dingtalk: https://oapi.dingtalk.com/robot/send?access_token=0bae3cc00e4b1a4a950ce5dedc2bc456b54b9aaa0811d0c43b2a1dac57ef0cec

